---
master:
  hosts:
    master001:
      ansible_host: 1.95.150.226
      ansible_user: root
      peer_ip: 10.110.0.2
workers:
  hosts:
    worker001:
      ansible_host: 117.72.111.75
      ansible_user: root
      peer_ip: 10.110.0.3
    worker002:
      ansible_host: 1.95.165.30
      ansible_user: root
      peer_ip: 10.110.0.4
    jenkins:
      ansible_host: 14.103.141.165
      ansible_user: root
      peer_ip: 10.110.0.7
cicd:
  hosts:
    jenkins:
      ansible_host: 14.103.141.165
      ansible_user: root
      peer_ip: 10.110.0.7
    jenkins001:
      ansible_host: 150.230.210.99
      ansible_user: ubuntu
      peer_ip: 10.110.0.5
    jenkins002:
      ansible_host: 158.101.133.80
      ansible_user: ubuntu   
      peer_ip: 10.110.0.6


cluster:
  vars:
    ansible_python_interpreter: /usr/bin/python3.10
  children:
    master:
    workers:

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3.10
  children:
    master:
    workers:
    cicd: